### ISSUE TITLE
The cpu and gpu problem

### ISSUE THREAD

**Issue by JBoRu** [lanyunshi/Multi-hopComplexKBQA#15]
Hi,
  Thanks for your contributions! When i run "sh WBQ_Runner.sh" as your command in Readme.md. The error occured as follows:
    
![image](https://user-images.githubusercontent.com/38073482/94146158-1cd57980-fea6-11ea-8252-730953899982.png)

   Hoping that you can give me some hlpe! Thanks again!

**Comment by counten** [comment]
how do you solve this problem, it occors to me now

**Comment by Forever-Z88** [comment]
Hello, have you solved this problem? I also encountered this problem. Looking forward to your reply, thank you!
