### ISSUE TITLE
the meaning of [mg] in FilterEnglishTriplts.py

### ISSUE THREAD

**Issue by counten** [lanyunshi/Multi-hopComplexKBQA#19]
I use this file to filter the freebase dump, but it filter all,  why do you use "[mg]" in the regx pattern

**Comment by lanyunshi** [comment]
Hi,

Are you using the raw Freebase dump? "[mg] in the regx pattern" indicates that we consider the triplets with [mg] mid, which is the format of the entities in Freebase. For other language triplets, we filter them out. 

Can you show me some triplets in your raw dump?

Best,
Yunshi

**Comment by counten** [comment]
yes, I download freebase dump from official website, and these are some lines  at the head of freebase-rdf-dump. I do not find  [mg]

```
<http://rdf.freebase.com/ns/award.award_winner>	<http://rdf.freebase.com/ns/type.type.instance>	<http://rdf.freebase.com/ns/m.01v3v75>	.
<http://rdf.freebase.com/ns/award.award_winner>	<http://rdf.freebase.com/ns/type.type.instance>	<http://rdf.freebase.com/ns/m.05xzqqh>	.
<http://rdf.freebase.com/ns/award.award_winner>	<http://rdf.freebase.com/ns/type.type.instance>	<http://rdf.freebase.com/ns/m.0jvby5>	.
<http://rdf.freebase.com/ns/award.award_winner>	<http://rdf.freebase.com/ns/type.type.instance>	<http://rdf.freebase.com/ns/m.0jzfb6>	.
<http://rdf.freebase.com/ns/award.award_winner>	<http://rdf.freebase.com/ns/type.type.instance>	<http://rdf.freebase.com/ns/m.0y_4w3_>	.
<http://rdf.freebase.com/ns/award.award_winner>	<http://rdf.freebase.com/ns/type.type.instance>	<http://rdf.freebase.com/ns/m.04gh45>	.
<http://rdf.freebase.com/ns/award.award_winner>	<http://rdf.freebase.com/ns/type.type.instance>	<http://rdf.freebase.com/ns/m.0p9973n>	.
<http://rdf.freebase.com/ns/award.award_winner>	<http://rdf.freebase.com/ns/type.type.instance>	<http://rdf.freebase.com/ns/m.05jvs8>	.
<http://rdf.freebase.com/ns/award.award_winner>	<http://rdf.freebase.com/ns/type.type.instance>	<http://rdf.freebase.com/ns/m.0404b3s>	.
```

**Comment by lanyunshi** [comment]
The samples that you provided will be filtered out as it doesn't match any of the regex patterns. The triplet below (I just give a fake example) will match the first regex pattern ''re_ns_ns'' (this pattern will match the triplet whose head entity is a mid and tail entity is also a mid). It's strange that you obtain nothing after running the code, maybe you can investigate the code by figuring out which unexcepted pattern is matched for a certain triplet

<http://rdf.freebase.com/ns/m.01v3v75>      <http://rdf.freebase.com/ns/type.type.instance> <http://rdf.freebase.com/ns/m.01v3v75>  .

**Comment by counten** [comment]
Thanks a lot, I finally find out the problem , the regex pattern from you works fine.
