### ISSUE TITLE
Python: TypeError: unsupported operand type(s) for +=: 'float' and 'list'

### ISSUE THREAD

**Issue by lzw429** [lanyunshi/Multi-hopComplexKBQA#2]
https://github.com/lanyunshi/Multi-hopComplexKBQA/blob/df6bf3f2608534015e528799e828fb0c5d5203fe/code/KBQA_Runner.py#L253

I'm using Python 3.7.6. There's an error when I'm trying to run:
```
TypeError: unsupported operand type(s) for +=: 'float' and 'list' 
```
I guess it should be `topic_score = topic_score + 0. if ...`

**Comment by lanyunshi** [comment]
May I know which dataset you are running?

**Comment by lzw429** [comment]
> May I know which dataset you are running?

I'm running it on dataset CQ.

**Comment by lanyunshi** [comment]
Can you print out ''te[w][0]'' or ''te[w]''?

**Comment by lzw429** [comment]
> Can you print out ''te[w][0]'' or ''te[w]''?

they are `[0.003073975978407299, 'anger management']` and `0.003073975978407299` respectively.

**Comment by lanyunshi** [comment]
I haven't encountered such an issue. I think the problem is that the 'topic_score' is a list in your case, but I have set it as a scalar at the beginning, can you double-check whether 'tokenizer.dataset' is 'CQ' or the 'topic_score' is a scalar?

**Comment by lzw429** [comment]
> I haven't encountered such an issue. I think the problem is that the 'topic_score' is a list in your case, but I have set it as a scalar at the beginning, can you double-check whether 'tokenizer.dataset' is 'CQ' or the 'topic_score' is a scalar?

I found that tokenizer.data is wrong...
Because the `data` is not a subdirectory of `code`, so I changed the default program parameter in the `.sh` and obtained the wrong value.

I've fixed this issue and thanks a lot.
